# Generated by Django 4.2.3 on 2023-09-05 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, default='0', max_length=250, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(db_index=True, default='0', max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 14, 12, 44, 38746, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
