# Generated by Django 4.2.3 on 2023-09-07 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_datetime_created_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fa',
            field=models.CharField(db_index=True, max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 49, 23, 548212, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
