# Generated by Django 4.2.3 on 2023-09-07 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_name_en_alter_category_name_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 11, 40, 42, 504009, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
