# Generated by Django 4.2.3 on 2023-09-08 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 13, 58, 46, 360, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
