# Generated by Django 4.2.3 on 2023-09-08 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 14, 22, 0, 48783, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='price'),
        ),
    ]
