# Generated by Django 4.2.3 on 2023-09-07 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 11, 40, 42, 519652, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
